### ISSUE TITLE
android friendly

### ISSUE THREAD

**Issue by 1kaiser** [adafruit/Adafruit-SHT4x-Trinkey-PCB#1]
can androud device can be used for logging as Termux or tmux is available in them ??

**Comment by BlitzCityDIY** [comment]
we have examples showing desktop logging with python over Serial: https://learn.adafruit.com/adafruit-sht4x-trinkey/logging-sht4x-data-with-cpython

the trinkey runs an Arduino sketch that outputs the data in a CSV format. in theory if your android device has a way to access the COM port then you should be able to.

**Comment by 1kaiser** [comment]
if the android device  is just a mobile phone

**Comment by BlitzCityDIY** [comment]
you would have to experiment with it. we have documentation on using CircuitPython with an Android phone that might have some helpful hints: https://adafruit-playground.com/u/BlitzCityDIY/pages/using-android-with-circuitpython

for more direct project help we recommend folks go to our Discord: [adafru.it/discord](adafru.it/discord)
